version = 1
SPDX-PackageName = "odh-alpinebits-server"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/odh-alpinebits-server"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".pre-commit-config.yaml", "LICENSE", ".env.example", "alpine_bits_rgb.png", "**.properties", "application-spring/src/main/resources/**", "odh-inventory/impl/src/main/resources/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
